
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/anirudh/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.6.0 - arm64
...
